# VARIABLES CHANGED AT RUNTIME
CAMERA_ZOOM_AMOUNT = 1
CAMERA_AREA_WIDTH_MODIFIER = 0
CAMERA_AREA_HEIGHT_MODIFIER = 0

# UNCHANGING VARIABLES
MOVEMENT_SPEED_VARIABLE = 4
MOVEMENT_SPEED_RUN_MULTIPLIER = 2