CAMERA_ZOOM_LEVEL = 2

UPDATE_SCREEN_DIV_DENOM = 2

ZOOM_LEVELS = [#(1, 0),
    (2, (2/1)),
    (3, (2/2)),
    (4, (2/3)),
    (5, (2/4)),
    (6, (2/5))
]

MOVEMENT_SPEED_VARIABLE = 4
MOVEMENT_SPEED_RUN_MULTIPLIER = 2